/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'arrizabalaga' at '6/26/14 11:55 PM' with Gradle 1.12
 *
 * @author arrizabalaga, @date 6/26/14 11:55 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
