/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'arrizabalaga' at '6/26/14 11:55 PM' with Gradle 1.12
 *
 * @author arrizabalaga, @date 6/26/14 11:55 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
